[package]
name = "MatrizGui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

